### ISSUE TITLE
Refactor permissions sheets

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1590]
## TODO

- [ ] ~review is confusing, and not ideal when being use in bulk~
- [x] stats for policy numbers could be helpful. Including articles covered by policy
- [ ] ~release process needs roll back process~
- [ ] ~allow contribution including orcid~
- [ ] ~contribution could be streamlined. Including finding forms internally etc~
- [ ] Have publisher names for 'parent policy' be a live dropdown
- [ ] change ‘,’ to ‘;’ in ID feilds to get around commas in publisher name.
- [ ] Separate data into many sheets so you don’t need it all open to change something
- [x] delete “Post-publication Pre-print Update Allowed"
- [x] make all licenses english in names
- [ ] use importranges on keys so that we only have one to maintain
- [x] Re-org column order in permissions sheet to be easier to work with
- [ ] make formula for journal full able to be totally turned off + ignore blank to keep load down and avoid errors
- [x] make it so that natalia doesn't need to complete the review sheet to bump dates
- [ ] make sure it's known that once this change happens there will be a live relationship between the database and the api
- [ ] ~update contribution instructions~
- [ ] ~review if watchete is working well for us~
- [x] wiley journals have two issns that are the same. E.g `0108-7673, 0108-7673`.
- [ ] ~take a pass a refreshing some embargo data even though we don't think it's changed~
- [ ] make sure subject repo sheet gets merged into main data
- [ ] use data validation on publisher names

Refactor goals:

* Reduce complexity / duplication
* Align design with usage
* Make the editing experience easier & safer

Big changes:

## Retire contribution mechanism. 

* Have "updated at" be done by a formula so that when the data changes the updated date automatically changes.

## Split data types into their own sheets. 

* Allow export to read right from raw data (not imported data).

## Update data structure. 

* Retire old columns
* Update headers to align with API.

**Comment by JosephMcArthur** [comment]
The plan here is to wait until Mark has parity with current permissions and then make database changes the day we're ready to push out so we limit time maintaining several formats.

Some more TODOs:

- [ ] Have publisher names for 'parent policy' be a live dropdown
- [ ] change ‘,’ to ‘;’ in ID feilds to get around commas in publisher name.
- [ ] Separate data into many sheets so you don’t need it all open to change something
- [ ] delete “Post-publication Pre-print Update Allowed"
- [ ] make all licenses english in names
- [ ] use importranges on keys so that we only have one to maintain
- [ ] Re-org column order in permissions sheet to be easier to work with
- [ ] make formula for journal full able to be totally turned off + ignore blank to keep load down and avoid errors
- [ ] make it so that natalia doesn't need to complete the review sheet to bump dates
- [ ] make sure it's known that once this change happens there will be a live relationship between the database and the api
- [ ] update contribution instructions 
- [ ] review if watchete is working well for us
- [ ]

**Comment by JosephMcArthur** [comment]
Once I've updated timestamp stuff 15 minute updates can be enabled.

**Comment by JosephMcArthur** [comment]
Also flagging this as a bug as I think it's causing several import issues

**Comment by JosephMcArthur** [comment]
From #1598

> It's easy to mess things up when editing the data.
> 
> e.g:
> 
> * If we have a link, is it being automatically monitored?
> * Are fields getting the input they expect?
> * Are our require fields done?
> * Notes triage and highlighting
> 
> Lots of little things like that would be good.

**Comment by JosephMcArthur** [comment]
Desirable to be able to force an index update so that natalia can verify her changes on the api before confirming with external people

**Comment by JosephMcArthur** [comment]
Remove spaces from exports

**Comment by natalianorori** [comment]
Changes to the publisher's prototype sheet
- [ ]Make everything that can be standardised a dropdown 
- [ ]Make record first added column a time stamp formula (when the first row was created, timestamp) 
- [ ]Make the reviewer field always Natalia@openaccessbutton.org 
- [ ]Have publisher names for parent policy to be a dropdown 
- [ ]Move subject specific repos to main publisher sheet

**Comment by natalianorori** [comment]
@JosephMcArthur , I have completed all the items in the list above. The only thing left to do, which should be a separate issue  and done in the future, is to convert all the archive links into perma links. Let me know when you have checked the prototype to implement the changes for journals and affiliations as well.

**Comment by natalianorori** [comment]
@markmacgillivray , we’ve been working on this for a little while and want to check in with you.

We are breaking down the Permissions Checker Data sheet into 3 sheets: Publishers data, Journals data, and affiliations data. 
Rather than having a massive sheet for data management that then exports to the smaller export sheets, we’re just going to have a few smaller and simpler sheets to manage data that can be directly exported to the API. This should simplify things quite a bit for us.

We have created publishers OARights data prototype to test some of the changes we plan to implement. The changes we think you need to know about include: 

- This sheet has a new URL (we’ve made it at a new place so we can maintain the old one as long as needed)

- Retired 8 old columns that should no longer be used by the API, but were once used. 

- Expanded archiving locations allowed. We now display data on different repository types, not just institutional repositories. This shouldn’t affect any of the systems logic, or structure, but a heads up.

- Using complete timestamps (including minutes and seconds) to record the date and time a record is first added, and last updated. This should help with pulling changes.

- Changed separators in `id` column from “,” to “;”

- Changed column header name “Policy_Full_Text” to “Archiving_Policy_Unarchived”.

While we’ve made many changes, our intent was that this should be a “drop in” replacement with few to no changes needed on your end.

If that isn’t the case, can you let us know so we can adjust? Otherwise, can you give us the all clear to propagate these changes to the other sheets?

**Comment by markmacgillivray** [comment]
Yeah they don't make much difference but will definitely need some specific changes made. I will need to check which columns you've removed and change how those IDs are separated, and change the column rename for the one that was altered.

Do you mean there are now four sheets to pull from, or still only the three new ones? e.g. is the OARights one an additional sheet? Are the previous three I already connected to on dev needing to change now? I've noticed google sheets still takes a very long time to generate them when they're opened.

Note that if it's a hassle for you to add more specific timestamps and not something you need, don't bother doing it. It doesn't make any difference to how we import the data anyway. I did mention a while ago that having timestamps could be beneficial if we did it in a different way, but since we're not doing it in that different way it doesn't matter. The same goes for the ID separators - it makes no difference if you use comma , or ; as long as I know which one you want me to split on, and as long as the ID texts don't include the one you want split on. Since they're not actually unique IDs the system can't use them as such anyway.

I mentioned to Joe recently I do wonder if it would be worth us doing more up-front planning of this sort of work though, because it's possible we're not making the best overall decisions for how this could be done. e.g. there may be things that are easy to do on the backend that you/Joe don't know about, and there may be things that are hard/easy for you to do on the sheets but I don't know about, because I have no idea what you really have to do in the sheets in the first place.

There's always the trade-off between trying to co-ordinate our work and trying to make sure progress can be made individually, which may mean potential inefficiencies are worth it anyway, particularly when we need to get quick prototypes or visually satisfying results to funders. But if those inefficiencies cost us all more time later, then we're not actually saving long term. We may be able to move to a more planned approach now that we have a longer term funding cycle in place.

**Comment by JosephMcArthur** [comment]
> Yeah they don't make much difference but will definitely need some specific changes made. I will need to check which columns you've removed and change how those IDs are separated, and change the column rename for the one that was altered.

@natalianorori any chance we can list out the removed columns today so Mark has them to hand for tomorrow?

> Do you mean there are now four sheets to pull from, or still only the three new ones? e.g. is the OARights one an additional sheet? Are the previous three I already connected to on dev needing to change now? I've noticed google sheets still takes a very long time to generate them when they're opened.

The three we're proposing here replace the three we currently have. The idea is that these will be much faster to generate.

> Note that if it's a hassle for you to add more specific timestamps and not something you need, don't bother doing it. It doesn't make any difference to how we import the data anyway. I did mention a while ago that having timestamps could be beneficial if we did it in a different way, but since we're not doing it in that different way it doesn't matter. The same goes for the ID separators - it makes no difference if you use comma , or ; as long as I know which one you want me to split on, and as long as the ID texts don't include the one you want split on. Since they're not actually unique IDs the system can't use them as such anyway.

What are the types of timestamps you'd want? I think we could likely output those easily.
There are commas in the actual values anyway, so using `,` turns out to have been a bad move. Hence, this change still being desirable.

> I mentioned to Joe recently I do wonder if it would be worth us doing more up-front planning of this sort of work though, because it's possible we're not making the best overall decisions for how this could be done. e.g. there may be things that are easy to do on the backend that you/Joe don't know about, and there may be things that are hard/easy for you to do on the sheets but I don't know about, because I have no idea what you really have to do in the sheets in the first place.

Shall we, regardless of progress above, take some time to show you more about the data management here?

> There's always the trade-off between trying to co-ordinate our work and trying to make sure progress can be made individually, which may mean potential inefficiencies are worth it anyway, particularly when we need to get quick prototypes or visually satisfying results to funders. But if those inefficiencies cost us all more time later, then we're not actually saving long term. We may be able to move to a more planned approach now that we have a longer term funding cycle in place.

I'm mainly riding off of co-ordination we did here previously, just actually implementing it has been delayed vs when I expected. We had planned to check in a bit earlier, but actually implementing these changes was pretty fast so in the end it seemed easier to present you with changes we thought were highly likely to be useful in a form that was as concrete as possible. Anyway... generally agree with this point.

**Comment by markmacgillivray** [comment]
For the timestamps I don't use them at all so they can be whatever suits you best for processing the data / what you want to see in the results.

For going over what the data management is, yeah I think at some point we should put some time into joining up what we all understand about the parts of the process :) not needed just to get this done though, so can be scheduled for later.

**Comment by natalianorori** [comment]
@markmacgillivray The columns removed are:
Licence(s)_Allowed
Post-publication_Pre-print_Update_Allowed
Can_Authors_Opt_Out
Policy_Landing_Page
Archived_Full_Text_Link
Funding_Proportion_Required
Issues
Policy_Full_Text >> replaced to Archiving_Policy_Unarchived

**Comment by JosephMcArthur** [comment]
This is assigned to me at the moment, but, @markmacgillivray are you good to move ahead here with trying to use the new V5 sheets?

**Comment by markmacgillivray** [comment]
Where are the new sheets? You may have told me already but I'm not remembering things at the moment. There should be four now right?

**Comment by JosephMcArthur** [comment]
The new one is here: https://docs.google.com/spreadsheets/d/11rsHmef1j9Q9Xb0WtQ_BklQceaSkkFEIm7tJ4qz0fJk/edit#gid=2103194526.

There are four new sheets in total, yes, but the idea is that what we're sending you here will replace (hopefully –– easily... see above) the three previously.

**Comment by markmacgillivray** [comment]
I've tried writing some fairly big answers to this. I'm not really sure what's best to say though. So instead I'll ask if you can be more specific about what you're asking me to move ahead to? We can discuss the more general big answers later.

**Comment by JosephMcArthur** [comment]
Sounds like we should chat live.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur



On Wed, Jul 21, 2021 at 12:21 AM, markmacgillivray ***@***.***

**Comment by markmacgillivray** [comment]
Can discuss this week if you want to.

**Comment by markmacgillivray** [comment]
Following up after talking to Joe about this last week, the new sheet as-is just now would be fine, however below are some recommendations to consider for generally making sheets easier to interoperate with a backend system. We don't NEED to do these for the permissions system, and it could be worth us discussing further, or we can just go ahead with the sheet you've already produced.

* simplify column names. Use only lowercase a to z characters, use underscores instead of spaces, don't have more than one space next to each other, don't start or end column names with spaces. This is not too critical as long as it's acceptable that the backend would do this simplification if you did not, e.g. don't rely on column names being unique on the basis of capitalisations or containing dashes.
* use "dot notation" to represent "depth" in resulting API output - and DON'T use dots (full stops, periods, whatever you want to call them) for anything else in a column name (this isn't a problem if you're already following the previous point anyway). For example with permissions the API response contains a key called "meta" which points to an object, and that object contains a key called "monitoring". Ideally it would be better not to nest such content unless there is a functional need to do so. However, it is what it is now, so in the sheet, the column that contains the value to appear there could be named meta.monitoring
* nesting lists of objects has to be done carefully. For example we have a "licences" key in the API results that points to a list of objects, each of which has a "type" key and a "terms" key. This could be identified by dot notation as columns called licences.type and licences.terms, and the values within the cells could be separated by a comma, BUT it would be necessary that the number and order of comma-separated values in those cells matches. E.g. if you had three licence types but only terms for the first and third, the licences.terms field would need to contain something like term1, , term3 (note the empty space). Again ideally it would be better to avoid this structural complexity altogether unless it is functionally unavoidable, but as it is what it is, we just need to agree some convention on these edge cases.
* it's not the case in these permissions sheets, but IF we had to represent complex nested and listed objects within sheets for import to an API, we'd also be better to come up with an agreement on how we would represent those in the sheet so that we could generalise that problem too (the simplest answer is manually writing JSON in those fields, more complex would be spreading the data on multiple rows, or using a pointer mechanism to point from a cell to a separate sheet containing the complex data to be listed)
* commas are typically the signifier for splitting values into lists. For example in the permissions data the ID field has multiple IDs separated by commas. The new sheet changes this to apostrophes. Unfortunately, it is possible that either one could occur in the real text values of that field, such as using publisher names as IDs. This is why those are not really very good IDs in the first place. It would be better to use something else for an ID where this problem cannot arise. It is also possible that some fields may contain commas where we would NOT intend to split those values into a list. So we would need a convention on where to use commas or not. I would recommend that content should just not contain ANY commas unless the commas are intended for signifying lists, but this can be quite restrictive if we want to provide longer text content or certain number formats, OR we signify lists explicitly by using the common json notation for lists - that would be using square brackets in a cell where the values should be treated as a list, and within those square brackets commas will ONLY be acceptable as value separations. So in the cell you would write [value1, value2, value3]. In the case of publisher names, I'd ask why is it that we need those publisher names to contain the commas anyway, can't we just write the publisher names without the commas - that depends on why we are using them, see the next points.
* What is the reason for having to use the publisher names as IDs? If we have to achieve exact matches on those publisher names, why do we have more than one publisher name as an ID? Could we ensure we have just one name provided? If the aim instead is to potentially match more names rather than make a guaranteed unique match, see the next point. Having a better understanding of the requirements could help us make better decisions here.
* If the function of the publisher names is to FIND the records about those publishers, it would be better that the publisher name field is just a metadata field that we search within. That way you can write different variations of the publisher name if desired, and any punctuation can just be thrown away as we would search on the main signifying strings. It wouldn't matter how you separate different publisher names in the field, because the backend would not try to analyse them. Note though that this approach means that publisher names that are a subset of other names can become problematic, so we would need to agree a convention for how the backend is expected to find them. This problem can exist even with the comma-separating (or apostrophe-separating) approach too. For example if someone tries to find "Wiley" then how would we know whether to return "Wiley Blackwell" or "Wiley Something Else". If there are definitely not multiple rows likely to match, then a text search wouldn't matter if we wrote that in a column as "Wiley Blackwell, Wiley" or whatever - we just search the text.

Although we can proceed without these changes, using them would mean that rather than having to write a specific import function for a given sheet and then maintaining and updating it when the sheet changes, we can have sheets that meet a certain convention and are always ingestable in an understood way by the API. That "convention" I'm referring to is basically simplifications that make it easy to translate from the flat structure of a sheet to the notation necessary for complex data structure (JSON in our case).

I'd need to do a little work either way, whether we use the new sheet as is or whether we try to move it more towards the recommendations above, because we already do have a specific import algorithm for the permissions sheets that I'd need to alter.

It's also likely in the case of permissions (and in other cases) that there would be additional processing required anyway, e.g. sometimes we look up additional sources to enrich the data coming from the sheet - but that is work that is unavoidable and has to be unique to a given sheet anyway, whereas the points above are generalisable.

Happy to discuss further.

**Comment by natalianorori** [comment]
The changes done on Publishers have been added to affiliations here: https://docs.google.com/spreadsheets/d/1J4WhZjPsAjpoogsj7wSTQGJPguo7TiSe0uNcrvyd_OM/edit#gid=1293771767

**Comment by JosephMcArthur** [comment]
@JosephMcArthur to do the same for journals. Natalia ran out of time.

**Comment by JosephMcArthur** [comment]
@markmacgillivray, I've done some work to move `publishers` and `affiliations` over to new sheets. Assigning this to you as it would be great to get the data we currently have feeding permissions switched out for these. `Journals` is still a TODO on my end, it's more complex.

* Publisher: https://docs.google.com/spreadsheets/d/11rsHmef1j9Q9Xb0WtQ_BklQceaSkkFEIm7tJ4qz0fJk/edit#gid=2103194526
* Affiliations: https://docs.google.com/spreadsheets/d/15fa1DADj6y_3aZQcP9-zBalhaThxzZw9dyEbxMBBb5Y/edit#gid=1810976998

As I did that today, I updated what Natalia had already done to include: 

> simplify column names. Use only lowercase a to z characters, use underscores instead of spaces, don't have more than one space next to each other, don't start or end column names with spaces
> use "dot notation" to represent "depth" in resulting API output

I also changed the name of "Publisher PDF, Postprint, Preprint" in the data to match what we actually have come out in the API.

I wasn't able to change other things you laid out, but, I hope these changes are directionally correct (and I don't think many of the things you touched on impacted this dataset).

Of note, while doing it, I think I actually found some fields in the data we're expecting to be present in the API that don't actually seem to be. So, I gave them new reasonable names too.

- [ ] Note to self: I needed to correct the added / updated dates in the new data. - @JosephMcArthur

**Comment by JosephMcArthur** [comment]
@markmacgillivray, journals data is here now: https://docs.google.com/spreadsheets/d/1ZTcYJUzhNJYIuxsjKzdVFCbOhJsviVik-8K1DpU7-eE/edit#gid=604629055.

Of note here, I introduced a new concept here in `hide.journal_sheet_row` & `hide.publisher_sheet_row`. I'm proposing a `hide.` namespace where the data might get imported but not displayed in the resulting API. In this case, it helps me not need to duplicate sheets -- one with the columns and one without. I can change it if this is actually harder than I'd expect.

> Note to self: I needed to correct the added / updated dates in the new data. - @JosephMcArthur

nb. I still need to transfer dates, but, that shouldn't be hard and is best done in one move (and that date of that move will depend on the date of transfer).

@markmacgillivray, over to you here now.

**Comment by markmacgillivray** [comment]
I didn't do anything with this so far this week, will get to it next week.

**Comment by markmacgillivray** [comment]
Some points for review when we next talk (or before, if you want to answer here):

* is this "hide" idea something you want across any sheet that we may import from, or just from permissions?
* there are still some column names with mixed case, such as Human_Readable_Name - is that a mistake, or do you really need that to be the name?
* how do you want to distinguish between notes and internal_notes? Should internal_notes really be a hide. column?
* it looks like you have colour-coding in the sheet to roughly differentiate between object groups, but then there are still some mixtures such as issuer.type appearing within the meta. colour-coded section. Is this just a coincidence and I don't need to use colours to check, or are there some mistakes here?
* issuer. object values that used to exist seem not to now, should they have been merged into other objects, or are they OK to now be top-level values where that now appears to be the case? e.g. has_policy
* the first column of the publisher sheet has no name. Is it supposed to be "id"?
* the last two columns of the publisher sheet appear to have dates in them instead of names - what should they be called?
* there used to be multiple licences, and then a separate licence field, is there now always only one?
* licences used to be objects with the licence and the terms, then we separated those out at the top level anyway, so should those just be two separate columns now as they appear in the sheet, e.g. licence and licence_terms?
* we previously normalised to "licence" rather than "license/licence". But now that no longer appears to be the case in the sheets. e.g. the journals sheet has a "license" column but then a "licence_terms" column. Could we normalise to one or the other within the sheets, then the API can just use whatever it finds in the sheet.
* meta.added appears to be a date but also appears to be a list. Why are there more than one date for added? What needs to be done with those?

**Comment by markmacgillivray** [comment]
* embargo_months used to be either empty or a number, now it appears to have statements in it. Do you expect these statements to be visible in results? Mixing numbers and text is not great when they have to be used as numbers - e.g. we need to use the number when it is present to add to the published date to see if it is before or after the current date. But if you want those text values to show up, then those numbers will have to be stored as text as well. That's not good practice for us to provide numeric content as strings in the API results, and also complicates all the code where we want to calculate current embargo status. It's fine to do if that's what you need, it's just not the same as before so pointing out these factors.
* What fields did you previously expect to see that weren't showing up? I've changed it now so that instead of trying to fix to an agreed set of output fields it's just going to output whatever fields it finds in the sheet, so that problem should go away anyway (once decided about the "hide" concept).

**Comment by markmacgillivray** [comment]
Unfortunately I have encountered a bigger problem. The latest sheets API, in the simplified way we use it, simplifies key names including removing dot notation. Given that we've already de-prioritised writing a full sheets API integration because it's not worthwhile, this means that dot notation in the sheets is not going to work. Also, since you have special cases such as fields you want in the sheet but want to hide, along with additional fields calculated that are not present in the sheet anyway such as embargo_end, this does not seem very amenable to a general solution, given our time constraints.

Are the other changes you made to these new sheets valuable for you compared to the old sheets? If so I will just customise the permissions imports to read from these sheets. Most of my questions in the previous two comments would still need answered for me to finish this though.

**Comment by JosephMcArthur** [comment]
notes from today:

`.hide` can be imported / indexed. Just doesn't mean put it in an api.
@markmacgillivray wants to look at sheets v4 to see if dots can be got or if we can use something other than dots (e.g "-") and the backend can interpret as a dot.
`Human_Readable_Name` mistake. Needs to be hide.human_readable_name`
`internal_notes` should be `hide.internal_notes`
color code doesn't matter
`has_policy` should be `issuer.has_policy`. `notes` too.
`the last two columns of the publisher sheet appear to have dates in them instead of names - what should they be called? `meta.added` &`meta.updated`. Stupid timestamp script has overwritten it.

**Comment by markmacgillivray** [comment]
I have checked we can get dots etc out of google sheets headers, and we can. They weren't showing up because of code I had added to clean them into a way that was compatible with how we had been using them in some older imports, so I had thought it would be simplest to make them more like how the old google sheets provided them, which did have certain constraints on the fields. But now they can be anything, it seems, because they are just the top row of the sheet - which is less good in some ways, but at least means we don't need to abandon the dot notation idea, which is much neater.

About the licences in DOAJ, and the "licence/licences" field - I'm a bit unclear what you mean above, it seems you're saying we don't need licences and only keep singular licence. But you are asking about keeping all licences we get from DOAJ. So yes, we could keep licences and only have it populated when we get multiples from DOAJ - but then, are you expecting it just to be a list of strings, or will it have to be a list of objects as it is in the current live permissions? If they're never being used like that, then just having a licences field that is a list of licence strings if they were present in DOAJ would be fine, I think.

**Comment by JosephMcArthur** [comment]
​I'm a bit unclear what you mean above, it seems you're saying we don't
need licences and only keep singular licence.


You're right. New plan. This is a refactor, and this isn't an essential
change, it's an enhancement. Let's just keep the behaviour of licences as
is.

Let me known when I can test stuff.


Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur



On Mon, Feb 14, 2022 at 10:52 PM, markmacgillivray ***@***.***

**Comment by markmacgillivray** [comment]
The work for the above comments has been done, and the new sheets now import almost completely. However there are still a few potential errors which I think are coming from the sheets themselves. Have a look at the keys being created, you can see there are still some with capitalisations such as Human_Readable_Name and inconsistent use of hide. prefix on that, and also there is at least one header that still appears to be a date string:

https://bg.beta.oa.works/permissions/journals/keys
https://bg.beta.oa.works/permissions/publishers/keys
https://bg.beta.oa.works/permissions/affiliations/keys

If the sheets can be reviewed and those small things fixed, a complete clean import should be possible (and is now quick and easy for me to do, as everything else looks like it is in place). 

This brings deposit refactor #1829 closer to being testable, but I noticed on running one of those SYP tests that the embed expects a field such as provenance.archiving_policy to be a list whereas it appears now to not be a list. Do you expect it still to be a list? If so I will fix for that. If not, and if there are other fields where you've changed the potential content (or fields where names may have changed in ways that impact the embed algorithm) then we would also need to make some changes to the embed to account for that, and then complete testing.

The above would also relate to the testing of the "new" embed itself (the one that is being separated from the website repo and converted solely to js). In #1842 I have been working through that, the documentation is not done yet but I am up to the point of wanting to test that new embed code on the dev site anyway. So if you can review my above paragraph and let me know if you're expecting some of those field values to be different (such as things that were lists are no longer lists) or important key name changes, then I will make those changes into the new embed code and we can test that on dev altogether as well.

Also I noted that the journal sheet still actually has "license" rather than "licence" so I put in a quick catch for that, but would be better to fix in the source.

Lastly, there are changes to the capitalisations of some of the contents - does that matter to you? I've altered the permissions code to account for it, such as where issuer.type used to be "journal" but is now "Journal", so the new API code does actually show it capitalised. However one that looks like probably an error is that sometimes "publishedVersion" is used in versions and other times it is "publisherVersion". So again I've made a change to the code to account for potential differences in how the versions are named, but would be better to have it correct in the sheet.

**Comment by JosephMcArthur** [comment]
> still some with capitalisations such as Human_Readable_Name and inconsistent use of hide. prefix on that,

Fixed

> and also there is at least one header that still appears to be a date string:

- [ ] Fixed. Although, I really need to fix the root issue which is the script

> Also I noted that the journal sheet still actually has "license" rather than "licence" so I put in a quick catch for that, but would be better to fix in the source.

Fixed at source

> However one that looks like probably an error is that sometimes "publishedVersion" is used in versions and other times it is "publisherVersion".

Fixed at source

> there are changes to the capitalisations of some of the contents - does that matter to you

It doesn't. Let me know if it's cleaner to have everything lowercased or something like that.

> https://bg.beta.oa.works/permissions/1058-4838
> https://bg.api.oa.works/permissions/1058-4838

Quick eyeball of these looks good - thank you!

> I noticed on running one of those SYP tests that the embed expects a field such as provenance.archiving_policy to be a list whereas it appears now to not be a list. Do you expect it still to be a list?

I'm honestly not sure. It seems like in this change we've better used new source fields to split up what used to have been lumped together. But, there is at least one case of two items in a field: `American Society of Tropical Medicine and Hygiene`. Is there a downside to keeping it a list?

**Comment by JosephMcArthur** [comment]
Ah, in your example links `archiving_policy_unarchived` looks like it may wanna be a list too! So, I'd err towards keeping it a list.

**Comment by JosephMcArthur** [comment]
Excellent! I have a couple of small TODOs above, but seemingly we can move the focus onto deposit now. So, I'll unassign you...

**Comment by markmacgillivray** [comment]
Yes

**Comment by JosephMcArthur** [comment]
Okay, addressed my small TODOs here. So, excited to close! 🥇
