### ISSUE TITLE
Upgrade stats InstantILL provides

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1821]
See email `InstantILL Follow Up` for suggestions / context. 

## TODO

- [ ] Decide if we should make other changes / upgrades
- [x] Make changes for Montana
- [x] Test changes with Montana
- [ ] If accepted, propagate changes to everyone

**Comment by JosephMcArthur** [comment]
This has been done for everyone. Yay, that'll do.
