### ISSUE TITLE
Run a complete accessibility audit & fixup of the embeds

### ISSUE THREAD

**Issue by sssoz** [oaworks/discussion#1851]
The current Embeds are not fully web-accessible. We want to ensure to meet WCAG 2.0 requirements for them. 

## TODO

- [x] Run thorough accessibility testing of all [embeds](https://github.com/oaworks/embed/blob/develop/oab_embed.js) ([InstantILL](https://oaworks.github.io/testing-ground/instantill/dev/default), [SYP](https://oaworks.github.io/testing-ground/shareyourpaper/dev/default))
  - [x] Automated testing (Lighthouse, axe-coconut, anything else?)
  - [x] Manual testing (with screen reader software, etc.) Done as part of https://github.com/oaworks/internal-planning/issues/330
- [x] Track down areas, create Github issues for each specific a11y issue
- [ ] Take a moment (maybe with @sssoz) to look at the language and copy and ensure it is written in simple English

[More details on this issue once we’re ready to start, @JosephMcArthur]

--- 

- Due to start  the week of 21st March
- **Preliminary work:** https://github.com/oaworks/discussion/issues/1842
- **Related:** https://github.com/oaworks/discussion/issues/1737

**Comment by sssoz** [comment]
@JosephMcArthur OK to close this one? 
https://github.com/oaworks/internal-planning/issues/330 kind of makes this one redundant now too

I ran Lighthouse and nothing comes up that can be picked up with automated testing. Manual testing is another story, but it’s nothing *truly* major, short of just recoding from scratch, or that requires a task on its own — I can add it all to https://github.com/oaworks/internal-planning/issues/330 

Though copy could be something we consider, but I think that becomes a bit out of scope for now.

**Comment by JosephMcArthur** [comment]
> @JosephMcArthur OK to close this one?
yes, please do the honors :)

> I ran Lighthouse and nothing comes up that can be picked up with automated testing.

fab

> but it’s nothing truly major, short of just recoding from scratch, or that requires a task on its own — I can add it all to https://github.com/oaworks/internal-planning/issues/330

I wouldn't suggest adding anything requiring major coding to https://github.com/oaworks/internal-planning/issues/330.

> Though copy could be something we consider, but I think that becomes a bit out of scope for now.

+1
